[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "shopsphere"
version = "0.1.0"
description = "Product Data Engineering Platform"
requires-python = ">=3.12"

dependencies = [
    "pandas",
    "requests"
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]